package exceptions

class CallWithErrorException() : Exception("Call returned with error") {
}